-- create tables for social media
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR (50) PRIMARY KEY NOT NULL,
    email VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR UNIQUE NOT NULL,
);

CREATE TABLE IF NOT EXISTS posts (
    upid PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR (50) PRIMARY KEY NOT NULL,
    content VARCHAR (256) PRIMARY KEY NOT NULL,
    likes DECIMAL NOT NULL,
);

CREATE TABLE IF NOT EXISTS likes (
    ulid PRIMARY KEY NOT NULL AUTO_INCREMENT
    upid DECIMAL,
    username VARCHAR (50) PRIMARY KEY NOT NULL,
);

CREATE TABLE IF NOT EXISTS likes (
    follower VARCHAR (50) PRIMARY KEY NOT NULL,
    followee VARCHAR (50) PRIMARY KEY NOT NULL,
);
